### ISSUE TITLE
Init migration from Geotoolkit to Apache SIS

### ISSUE THREAD

**Issue by eblondel** [openfigis/gems#17]
``Geotoolkit`` alias ``Geotk`` currently serves as laboratory for the ``Apache SIS`` project. Stable geotk artifacts are being moved to ``Apache SIS``. The purpose of this is to init the migration to Apache SIS. This will be done relying on the recent ``Geotk`` modules that yet started the migration relying on ``Apache SIS`` dependencies.

**Comment by eblondel** [comment]
The use of ``Apache SIS``  induces a change in the xml parsing of ``MD_BrowseGraphic`` https://issues.apache.org/jira/browse/SIS-119 Unfortunately, Geonetwork doesn't interprete well the new ``gmx:FileName`` and ``gmx:MimeFileType`` introduced by ``sis`` and doesn't display the ``thumbnail``.

**Comment by eblondel** [comment]
Migrating to apache sis ``0.6-jdk7-SNAPSHOT`` (with geotk ``4.0-SNAPSHOT``), asap to switch to 0.6 release, there is an issue to get the name of a ``PropertyType``. The problem occurs in particular in [FeatureUtils](https://github.com/openfigis/gems/blob/master/feature/src/main/java/org/fao/fi/gems/feature/FeatureUtils.java#L57), to get the name of the ``DefaultGeometryType``. This seems related to the recents gemes in the geotk modules.

**Comment by eblondel** [comment]
Two fix were provided with the past commit:

* Fix ``GML`` schema by forcing using a gml namespaces version < 3.2.1. This fixes wrong rendering in Geonetwork (for which version 2.6.x does not support GML 3.2.1)
* Fix ``TimePeriod`` missing id. Id is generated according to the GML schema ie calculating the period in ISO 8601. Time utils were refactored to rely on Joda Time library.

**Comment by eblondel** [comment]
Moving to recent releases for Apache SIS and Geotoolkit https://github.com/openfigis/gems/commit/4dfa30f96f23f59c7a9b569d6f020f577bee3927

**Comment by ceefour** [comment]
:+1:
